use Practice;
/*
-- HAVING CLAUSE
1. Having clause is used to specify conditions like where clause.
2. But having clause is used with group by command.
3. We cannot use where clause with group by command.
4. Where clause is used for filtering rows and having clause is used to filtering groups.
5. Where clause does not work with aggregate function like SUM, MIN, MAX, COUNT, AVG...
6. We can use having clause with aggreate functions.

*/

select *from Employee_Details;

select city, sum(Salary) as Total_Salary 
from Employee_Details
group by city
having city in ('Delhi');

-- CUBE AND ROLL-UP IN SQL

select city, sum(Salary) as Total_Salary
from Employee_Details 
group by city;

select city,gender, sum(Salary) as Total_Salary
from Employee_Details 
group by city, gender;

select city,gender, sum(Salary) as Total_Salary
from Employee_Details 
group by cube( city, gender);

-- Second method 
select city,gender, sum(Salary) as Total_Salary
from Employee_Details 
group by city, gender with cube;


/*
-- CUBE
- CUBE is an aggregate operator that produces a super-aggregate row.
- The summary row is displayed for every possible combination of goups in the result set.
- in addition to the usual rows provided by the GROUP By, it also provides the summary of the rows that the GROUP BY clause
by generates.
- The summary row display null in the result set byt at the same time returns all the values for those.
- Cube() in sql server produces the result set by generating all combinations of columns
specified in GROUP BY CUBE().
- Write a query to retrieve Sum of Salary grouped by all possible combinations of the 2 columns (City and Gender) as well as GRAND Total.
*/

-- ROLL UP
/*
- In addition to the usual rows that are generated by the GROUP BY
clause, it also introduees summary rows into the result set.
- It arranges the groups from the lowest to the highest.
- It is similar to CUBE operator but generates a result set that shows
goups arranged in a hierachical order.
- Group hierachy in the reuslt is dependent on the order in which the columns that are goruped are specified.
*/
select city,gender, sum(Salary) as Total_Salary
from Employee_Details 
group by rollup( city, gender);

select city,gender, sum(Salary) as Total_Salary
from Employee_Details 
group by city, gender with rollup;


